AllCops:
  Exclude:
    - Guardfile
    - 'vendor/**/*'
    - '.kitchen/**/*'
LineLength:
  Max: 120
HashSyntax:
  Exclude:
    - Rakefile
    - Berksfile
    - 'spec/**/*'
    - 'test/**/*'
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/WordArray:
  Exclude:
    - Rakefile
Metrics/MethodLength:
  Enabled: false
Lint/Eval:
  Enabled: false
